package com.allegrowatcher;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ALLEGRO_ID.
 */
public class AllegroId {

    private Long id;
    private Long allegro_id;

    public AllegroId() {
    }

    public AllegroId(Long id) {
        this.id = id;
    }

    public AllegroId(Long id, Long allegro_id) {
        this.id = id;
        this.allegro_id = allegro_id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getAllegro_id() {
        return allegro_id;
    }

    public void setAllegro_id(Long allegro_id) {
        this.allegro_id = allegro_id;
    }

}
