package com.allegrowatcher;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.allegrowatcher.AllegroId;
import com.allegrowatcher.FilterStorage;

import com.allegrowatcher.AllegroIdDao;
import com.allegrowatcher.FilterStorageDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig allegroIdDaoConfig;
    private final DaoConfig filterStorageDaoConfig;

    private final AllegroIdDao allegroIdDao;
    private final FilterStorageDao filterStorageDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        allegroIdDaoConfig = daoConfigMap.get(AllegroIdDao.class).clone();
        allegroIdDaoConfig.initIdentityScope(type);

        filterStorageDaoConfig = daoConfigMap.get(FilterStorageDao.class).clone();
        filterStorageDaoConfig.initIdentityScope(type);

        allegroIdDao = new AllegroIdDao(allegroIdDaoConfig, this);
        filterStorageDao = new FilterStorageDao(filterStorageDaoConfig, this);

        registerDao(AllegroId.class, allegroIdDao);
        registerDao(FilterStorage.class, filterStorageDao);
    }
    
    public void clear() {
        allegroIdDaoConfig.getIdentityScope().clear();
        filterStorageDaoConfig.getIdentityScope().clear();
    }

    public AllegroIdDao getAllegroIdDao() {
        return allegroIdDao;
    }

    public FilterStorageDao getFilterStorageDao() {
        return filterStorageDao;
    }

}
