package com.allegrowatcher;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table FILTER_STORAGE.
 */
public class FilterStorage {

    private Long id;
    private String keyword;
    private Integer category_id;
    private String category_name;
    private Integer price_min;
    private Integer price_max;
    private Integer condition;

    public FilterStorage() {
    }

    public FilterStorage(Long id) {
        this.id = id;
    }

    public FilterStorage(Long id, String keyword, Integer category_id, String category_name, Integer price_min, Integer price_max, Integer condition) {
        this.id = id;
        this.keyword = keyword;
        this.category_id = category_id;
        this.category_name = category_name;
        this.price_min = price_min;
        this.price_max = price_max;
        this.condition = condition;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getKeyword() {
        return keyword;
    }

    public void setKeyword(String keyword) {
        this.keyword = keyword;
    }

    public Integer getCategory_id() {
        return category_id;
    }

    public void setCategory_id(Integer category_id) {
        this.category_id = category_id;
    }

    public String getCategory_name() {
        return category_name;
    }

    public void setCategory_name(String category_name) {
        this.category_name = category_name;
    }

    public Integer getPrice_min() {
        return price_min;
    }

    public void setPrice_min(Integer price_min) {
        this.price_min = price_min;
    }

    public Integer getPrice_max() {
        return price_max;
    }

    public void setPrice_max(Integer price_max) {
        this.price_max = price_max;
    }

    public Integer getCondition() {
        return condition;
    }

    public void setCondition(Integer condition) {
        this.condition = condition;
    }

}
